# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*"

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os  }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py37",
          "ubuntu-py38",
        ]

        include:
          - name: ubuntu-py37
            python: "3.7"
            os: ubuntu-latest
            tox_env: py37
          - name: ubuntu-py38
            python: "3.8"
            os: ubuntu-latest
            tox_env: py38


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: test
        run: |
          tox -e py

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: |
          tox -e isort
          tox -e flake8
